### ISSUE TITLE
реплай для заметок

### ISSUE THREAD

**Issue by imadraude** [wardsenz/friendly-telegram#13]
можно отредачить заметки так, чтобы они при использовании медиа проходили проверку на реплай (если ты реплаишь командой, то медиа тоже отправляется реплаем)?

**Comment by aiexz** [comment]
Это и так есть

**Comment by imadraude** [comment]
> Это и так есть

разве? **медиа** отправляется просто в чат, без реплая

**Comment by aiexz** [comment]
Проверил только что
