### ISSUE TITLE
Почему нельзя не на хероку?

### ISSUE THREAD

**Issue by SsNipeR1** [wardsenz/friendly-telegram#16]
Реально почему нельзя просто на свою машину?

**Comment by wardsenz** [comment]
1. https://github.com/wardsenz/friendly-telegram#%D0%B2%D0%B0%D0%B6%D0%BD%D0%BE
2. https://ftg-ru.ga/

**Comment by SsNipeR1** [comment]
> 1. https://github.com/wardsenz/friendly-telegram#%D0%B2%D0%B0%D0%B6%D0%BD%D0%BE
> 2. https://ftg-ru.ga/

Спс
