### ISSUE TITLE
apt package request

### ISSUE THREAD

**Issue by semolik** [wardsenz/friendly-telegram#2]
ffmpeg
wand

**Comment by wardsenz** [comment]
> ffmpeg

Постараюсь добавить через билдпак или аптфайл, 

> wand
А модуль питона уже добавлю потом, если появится большой спрос на него. Потому что нет смысла увеличивать размер конечной сборки из-за одного единственного модуля для юзербота.

**Comment by wardsenz** [comment]
Решение из тг. Для ffmpeg:

```
apt-get install nodejs
npm install -g heroku
heroku login
git clone https://git.heroku.com/твой-апп.git
cd твой-апп
heroku git:remote -a твой-апп
echo "ffmpeg" >> Aptfile
git add Aptfile
git commit -m "apt-add"
git push heroku master
```

Вместо _твой-апп_ будет ссылка на апп в хероку. В настройках подписано как **Heroku Git URL**. 


Wand:

```
apt-get install nodejs
npm install -g heroku
heroku login
git clone https://git.heroku.com/твой-апп.git
cd твой-апп
heroku git:remote -a твой-апп
echo "wand==0.6.2" >> requirements.txt
git add requirements.txt
git commit -m "pip-add"
git push heroku master
```
