### ISSUE TITLE
ffmpeg

### ISSUE THREAD

**Issue by imadraude** [wardsenz/friendly-telegram#5]
возможно ли сделать так, чтобы модули, требующие ffmpeg, работали на хероку?

**Comment by wardsenz** [comment]
Кратко: Нет.

Уже пытались и тратили очень много времени на тесты. Сам обход уже найден - https://github.com/wardsenz/ftg/issues/2.  Но все попытки упираются в ограничения Heroku. На нашем стаке Heroku, где работает юзербот, а именно - Heroku-18 буквально нет подержки нужной нам библиотеки libvpx, и никак это не обойти. Так что либо терпеть, либо ставить на удаленный сервер. 
https://t.me/friendlytgbot_ru/216632
