### ISSUE TITLE
фтг мод на свою вдсину

### ISSUE THREAD

**Issue by tym4yk12160** [wardsenz/friendly-telegram#7]
когда будет фтг мод на свою вдсину, а?

**Comment by wardsenz** [comment]
`sudo apt update`
`sudo apt install python3 python3-pip git screen`
`sudo apt install python3-dev libwebp-dev libz-dev libjpeg-dev libopenjp2-7 libtiff5w libffi-dev libcairo2 neofetch dialog`
`git clone https://github.com/wardsenz/friendly-telegram`
`cd friendly-telegram`
`python3 -m friendly-telegram <аргументы>`
# Screen для сохранения сессии
`screen python3 -m friendly-telegram <аргументы>`

**Проблемы?**

**Comment by 1IxI1** [comment]
Нихуясу

**Comment by aiexz** [comment]
Мод устанавливается точно также как и оригинальная версия
